# Generated by Django 4.0.6 on 2022-07-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=5)),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('text', models.CharField(max_length=10000)),
                ('mp3File', models.FileField(upload_to='mp3')),
            ],
        ),
    ]
